--- #YAML:1.0
name: Net-OSCAR
version: 1.905
license: perl
distribution_type: module
requires:
  Digest::MD5: '>= 2.0'
  Scalar::Util: '>= 1.0'
  perl: 5.6.1
recommends:
  Test::More: '>= 0.01'
  XML::Parser: '>= 0.01'
build_requires: {}
conflicts: {}
provides:
  Net::OSCAR:
    file: OSCAR.pm
    version: 1.905
  Net::OSCAR::Buddylist:
    file: OSCAR/Buddylist.pm
    version: 1.905
  Net::OSCAR::Callbacks:
    file: OSCAR/Callbacks.pm
    version: 1.905
  Net::OSCAR::Common:
    file: OSCAR/Common.pm
    version: 1.905
  Net::OSCAR::Connection:
    file: OSCAR/Connection.pm
    version: 1.905
  Net::OSCAR::Connection::Chat:
    file: OSCAR/Connection/Chat.pm
    version: 1.905
  Net::OSCAR::Constants:
    file: OSCAR/Constants.pm
    version: 1.905
  Net::OSCAR::Proxy:
    file: OSCAR/Proxy.pm
    version: 1.905
  Net::OSCAR::Screenname:
    file: OSCAR/Screenname.pm
    version: 1.905
  Net::OSCAR::TLV:
    file: OSCAR/TLV.pm
    version: 1.905
  Net::OSCAR::Utility:
    file: OSCAR/Utility.pm
    version: 1.905
  Net::OSCAR::XML:
    file: OSCAR/XML.pm
    version: 1.905
  Net::OSCAR::XML::Template:
    file: OSCAR/XML/Template.pm
  Net::OSCAR::_BLInternal:
    file: OSCAR/_BLInternal.pm
    version: 1.905
generated_by: Module::Build version 0.21
